---
- hosts: 172.31.21.88
  become: yes
  tasks: 
   - name: Execute Linux Commands
     command: hostname -f
     register: myfirstaskresult

    
   - name: I want to see task result.
     debug: 
       msg: "{{myfirstaskresult}}" 
     