---
- hosts: 172.31.21.88
  become: yes
  tasks:
   - include_tasks: myfile.yml

   - name: I want to copy file from ansible master to node.
     copy:
      src: mystatic 
      dest: /home/ubuntu/mystaticfile
     notify: restartwebserver

   - name: I want to install webserver.
     apt:
      name: apache2
      state: present

   - name: Copy dynamic file into node server.
     template: 
       src: myindexfile.j2
       dest: /var/www/html/index.html

  # - name: Download files from internet.
    # get_url:
     #  url: 
      # dest:
       # force_basic_auth: yes

  handlers:                                 # to execute same tasks n number times just use handler.
   - name: restartwebserver
     service:
      name: apache 2
      state: restarted
     