---
- hosts: mywebservers
  become: yes
  tasks:
   - name: Install java on Ubuntu node
     apt:
      name: "{{myjavapackageonubuntu}}"
      state: present
     when: ansible_os_family == "Debian"

   - name: Install java on redhat node.
     yum: 
      name: "{{myjavapackageonredhat}}"
      state: present
     when: ansible_os_family == "Redhat"