---
- hosts: all
  become: yes
  gather-facts: yes #gathering information of node server. optional
  tasks:
   - name: I want to install webserver.
     apt:
      name: tree
      state: present
  
   - name: install git
     apt:
      name: git
      state: present