---
- hosts: all
  become: yes
  tasks:
   - name: I want to install webserver.
     apt: 
      name: apache2
      state: present
     when: ansible_os_famiily =="Debian"

   - name: I want to start the server.
     apt: 
      name: apache2
      state: started
     when: ansible_os_famiily =="Debian"